// src/utils/progressMovementMap.ts

export const progressMovementMap = [
  { week: 1, action: '動作1', title: 'P25 骨盆穩定術' },
  { week: 1, action: '動作2', title: 'P26 軀幹穩定術' },
  { week: 1, action: '動作3', title: 'P27 下肢伸展大法' },
  { week: 2, action: '動作1', title: 'P28 三足鼎立術' },
  { week: 2, action: '動作2', title: 'P29 足底核心大法' },
  { week: 2, action: '動作3', title: 'P30 腳踝穩定術' },
  { week: 3, action: '動作1', title: 'P31 單腳穩定術' },
  { week: 3, action: '動作2', title: 'P32 單腳平衡大法' },
  { week: 3, action: '動作3', title: 'P33 單腳平衡挑戰賽' },
  { week: 4, action: '動作1', title: 'P34 平衡情緒呼吸法' },
  { week: 4, action: '動作2', title: 'P35 冷靜呼吸法' },
  { week: 4, action: '動作3', title: 'P36 頭顱發光呼吸法' },
  { week: 5, action: '動作1', title: 'P40 肩胛骨中立術' },
  { week: 5, action: '動作2', title: 'P41 漂亮美背術' },
  { week: 5, action: '動作3', title: 'P42 肩胛骨穩定術' },
  { week: 6, action: '動作1', title: 'P43 挺胸擴背大法' },
  { week: 6, action: '動作2', title: 'P44 上肢伸展術' },
  { week: 6, action: '動作3', title: 'P45 肩膀不卡卡術' },
  { week: 7, action: '動作1', title: 'P37 軀幹核心穩定術' },
  { week: 7, action: '動作2', title: 'P38 平坦小腹大法' },
  { week: 7, action: '動作3', title: 'P39 軀幹後彎術' },
  { week: 8, action: '動作1', title: 'P46 快樂舒壓大法' },
  { week: 8, action: '動作2', title: 'P47 五體投地放鬆大法' },
  { week: 8, action: '動作3', title: 'P48 呼吸放鬆大法' },
];
