// src/utils/progressMovementMap.ts

export const progressMovementMap = [
  { week: 1, action: '動作1', title: 'P25 肩膀不聳肩術' },
  { week: 1, action: '動作2', title: 'P26 核心穩定術' },
  { week: 1, action: '動作3', title: 'P27 抗壓訓練大法' },
  { week: 2, action: '動作1', title: 'P28 拉弓箭開胸椎術' },
  { week: 2, action: '動作2', title: 'P29 性感側腰線訓練大法' },
  { week: 2, action: '動作3', title: 'P30 雙人合作-核心穩定術' },
  { week: 3, action: '動作1', title: 'P31 小腹縮小術' },
  { week: 3, action: '動作2', title: 'P32 小腹緊實大法' },
  { week: 3, action: '動作3', title: 'P33 雙人合作-骨盆穩定術' },
  { week: 4, action: '動作1', title: 'P34 髖膝穩定術' },
  { week: 4, action: '動作2', title: 'P35 女神蹲' },
  { week: 4, action: '動作3', title: 'P36 雙人合作-同心協力術' },
  { week: 5, action: '動作1', title: 'P37 修長手臂訓練大法' },
  { week: 5, action: '動作2', title: 'P38 早晨開機術' },
  { week: 5, action: '動作3', title: 'P39 雙人合作-棒式拍拍術' },
  { week: 6, action: '動作1', title: 'P40 喝水訓練大法' },
  { week: 6, action: '動作2', title: 'P41 美頸端正術' },
  { week: 6, action: '動作3', title: 'P42 胸椎轉轉術' },
  { week: 7, action: '動作1', title: 'P43 骨盆扭扭術' },
  { week: 7, action: '動作2', title: 'P44 提臀瘦大腿大法' },
  { week: 7, action: '動作3', title: 'P45 雕塑臀部大法' },
  { week: 8, action: '動作1', title: 'P46 心胸開闊術' },
  { week: 8, action: '動作2', title: 'P47 軀幹扭扭術' },
  { week: 8, action: '動作3', title: 'P48 世界上最好的伸展' },
];
